# Generated by Django 3.2.6 on 2021-08-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
